# <font color='blue'>Curso de Extensão: Introdução a Linguagem Python para Ciência de Dados - Aula 3 - Plotly</font>

### Plotly
 - Plotly é uma biblioteca Python que permite construir facilmente gráficos sofisticados.
 - Possui visualização de dados interativa
 - Permite criar gráficos que podem ser manipulados em tempo real, permitindo uma exploração de dados dinâmica e imersiva
 - Documentação: https://plotly.com/python/

In [3]:
import plotly.express as px

In [4]:
#!pip install plotly==5.1.0

In [5]:
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])


fig.show()

In [6]:
df = px.data.tips()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
df = px.data.tips()
fig = px.histogram(df, x="total_bill", color="sex", nbins=10)
fig.show()

In [9]:
fig = px.box(df, x="day", y="total_bill", color="sex")
fig.update_traces(quartilemethod="exclusive") # or "inclusive", or "linear" by default
fig.show()

In [10]:
fig = px.box(df, x="time", y="total_bill", points="all",color="sex")
fig.show()

In [11]:
df = px.data.stocks()
df.head()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708

In [12]:
df.describe()

             GOOG        AAPL        AMZN          FB        NFLX        MSFT
count  105.000000  105.000000  105.000000  105.000000  105.000000  105.000000
mean     1.046206    1.138536    1.393822    0.945121    1.540559    1.318059
std      0.077776    0.182109    0.140796    0.103350    0.200508    0.220662
min      0.888689    0.847200    1.000000    0.668718    1.000000    0.988547
25%      0.992924    1.000400    1.304091    0.879529    1.398876    1.142873
50%      1.036372    1.095429    1.420278    0.959968    1.560884    1.242431
75%      1.095189    1.236000    1.491702    1.016858    1.701605    1.543599
max      1.226504    1.678000    1.637494    1.123575    1.957665    1.802472

In [13]:
df = px.data.stocks()
fig = px.line(df, x="date", y=df.columns,
              hover_data={"date": "|%B %d, %Y"},
              title='custom tick labels')
fig.update_xaxes(
    dtick="M1",
    tickformat="%b\n%Y")
fig.show()

In [14]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')

fig = px.line(df, x='Date', y='AAPL.High', title='Time Series with Range Slider and Selectors')
fig.show()

In [15]:
df.describe()

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up
count,506.000000,506.000000,506.000000,506.000000,5.060000e+02,506.000000,506.000000,506.000000,506.000000
mean,112.935000,113.919447,111.942016,112.958340,4.317842e+07,110.459312,107.311385,112.739865,118.168345
std,11.287490,11.251892,11.263687,11.244744,1.985253e+07,10.537529,11.095804,10.595315,10.670752
min,90.000000,91.669998,89.470001,90.339996,1.147590e+07,89.008370,85.508858,94.047166,97.572721
25%,105.482500,106.349999,104.657501,105.672499,2.974240e+07,103.484803,97.011245,104.954875,111.052267
50%,112.889999,114.145001,111.800003,113.025002,3.747460e+07,110.821123,107.351628,112.799750,118.472542
75%,122.267498,123.497500,121.599998,122.179998,5.076395e+07,119.255457,114.812152,121.889416,128.515793
max,135.669998,136.270004,134.839996,135.509995,1.622063e+08,135.509995,127.289258,129.845000,138.805366

In [16]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')

fig = px.line(df, x='Date', y='AAPL.High', title='Time Series with Range Slider and Selectors')

fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)
fig.show()